name: "下班"

on:
  workflow_dispatch:
  schedule:
    - cron: "30 9 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
        
      - name: Run sign
        env: 
            MOGUDING_DEVICE: ${{ secrets.Device }}
            MOGUDING_PHONE: ${{ secrets.Phone }}
            MOGUDING_PASSWORD: ${{ secrets.Password }}
            MOGUDING_PROVINCE: ${{ secrets.Province }}
            MOGUDING_CITY: ${{ secrets.City }}
            MOGUDING_ADDRESS: ${{ secrets.Address }}
            MOGUDING_LONGITUDE: ${{ secrets.Longitude }}
            MOGUDING_LATITUDE: ${{ secrets.Latitude }}
            MOGUDING_TYPE: "END"
            MOGUDING_DESCRIPTION: ${{ secrets.Description }}
        run: php artisan moguding
